[package]
name = "resumidor-de-pdf"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
dotenv = "0.15.0"
anyhow = "1.0.100"
pdf-extract = "0.10.0"
clear_screen = "0.1.0"
colored = "3.0.0"
gemini-rust = "1.5.1"